services:
  mysql-db:
    image: mysql:8.0
    container_name: sportradar_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sporting_calendar
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"  # Host port 3307 -> Container port 3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: